### ISSUE TITLE
Document the usage of the whole `ml` subproject in the main README.md

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#102]
skeeelled/README.md, not skeeelled/ml/README.md

- [x] how to use the scrapers
- [x] datasets used (for Italian - scraped - and English)
- [x] what is a Transformer
- [x] components of the pipeline (language detector, bag of words, sentiment analysis...)
- [x] how to use the pipeline
- [x] measure of inference time for each step on CPU and on GPU (ex. on Google Colab)

**Comment by papadeiv** [comment]
Closed with commit [0b5d282](https://github.com/WEEE-Open/skeeelled/commit/0b5d282b93aea46856b4d5d785325594273dd19b).
