### ISSUE TITLE
Fix the various "Warning: Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#113]
Examples that come up in the browser's developer console navigating the website (specifically logging in, clicking on "Course", then "Start Simulation" and finishing it):
- [x] Check the render method of `ListGroup`.
- [x] Check the render method of `ListDefault`.
- [x] Check the render method of `ListEntryDefault`.
- [x] Check the render method of `Questions`.
- [x] Check the render method of `ListQuestions`.
- [x] Check the render method of `ListEntryQuestions`.
- [x] Check the render method of `ListSuggestion`.
- [x] Check the render method of `StartSimulation`.
- [x] Check the render method of `ListSimulationResult`.

It looks like we love technical debt lol.

**Comment by itIsJim** [comment]
> It looks like we love technical debt lol.

lol
