### ISSUE TITLE
What REST APIs should we use?

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#26]
What APIs should the backend implement in order to have a fully working frontend?

**Comment by aliGhanbari98** [comment]
**USER**
1. login
2. register
3. refreshToken
4. updateUser (information and settings)
5. getUserDataById (to feed the profile page)
6. getUserCourses
7. getUserResultsFromAnExam
8. getUserAnswers
9. getUserReceivedAnswers
10. getUserNewQuestinons (in enrolled courses)
11. logout

**Course**
1. createCourse
2. updateCourse
3. getAllCourses (gets certain parameters for filtering purposes)
4. addCourseToMyList
5. removeCoursefromMyList


**Question**
1. getQuestionsByCourseId (and other parameters for filtering purposes)
2. getNewQuestionsByCourseId
3. getAllQuestinos
4. getSimilarQuestions
5. createQuestion
6. updateQuestion
7. removeQuestion

**Answers**
1. getAnswersByQuestionId
2. getRepliesByAnswerId (?)
3. addAnswer
4. likeAnswer (?)
5. unlikeAnswer (?)
6. removeAnswer

**Exams**
No Idea how it's going to be implemented!

**Comment by e-caste** [comment]
### User

- updateUsername
- updateProfilePicture
- getUser -> all data no pass

#### Homepage

- getUserLastQuestion(limit: n)
- getUserLastAnswersAnswered(limit: n) -> made by user
- getUserLastAnswersReceived(limit: n) -> made by users to the user's questions
- getUserCoursesNewQuestions(limit: n)
- getUserCourses -> enrolled or teaching
- TODO getUserSimulationResults

#### Search

- getSearchResults(field: (course, question, answer...), string: x, tags: []...)
TODO: support search parameters

### Course

- getQuestionsAll(course: id)
- getQuestionsPaginated(course: id, n_questions, page_index)

**Comment by e-caste** [comment]
Solved with a recent meeting. New issues coming soon.
