### ISSUE TITLE
ML task analysis

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#3]
- [x] investigate pre-trained models that could be useful for our task
- [ ] take a look at the initial dataset

**Comment by papadeiv** [comment]
Models tested so far:
* MilaNLProc/feel-it-italian-sentiment
* neuraly/bert-base-italian-cased-sentiment
* dbmdz/bert-base-italian-cased
* Hate-speech-CNERG/dehatebert-mono-italian
* unideeplearning/polibert_sa

**Comment by e-caste** [comment]
Moved to #29
