### ISSUE TITLE
Remove all square brackets from string at inference time

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#76]
This is because the current model, https://huggingface.co/neuraly/bert-base-italian-cased-sentiment, uses the `[`, `]` characters to define mask tokens. This means that everything between those characters is ignored by the model.

With square brackets (neutral at 81%):
<img width="611" alt="Screenshot 2022-03-23 at 12 02 51" src="https://user-images.githubusercontent.com/48513706/159685159-ceb0119a-82f0-4d88-8521-aa585ec66c4d.png">

Without square brackets (negative at 77%):
<img width="623" alt="Screenshot 2022-03-23 at 12 03 19" src="https://user-images.githubusercontent.com/48513706/159685231-f27dcc8e-9390-496f-8219-1791c3f60f3c.png">

This issue stemmed from the suspicious results obtained by testing the Neuraly transformer (only 8% of accuracy against our currently labeled dataset) in commit https://github.com/WEEE-Open/skeeelled/commit/71fa6f98cdcd28aa060ce4352d071414d9c8adb1.

**Comment by papadeiv** [comment]
The issues are related to other characters' combination other than those associated to the masking. In commit [`7c76f85`](https://github.com/WEEE-Open/skeeelled/commit/7c76f85d139d27c5aa082669f6e86b9449942657) they have been removed from the inferred string but retained in the original comment. It is now functioning properly.
