### ISSUE TITLE
Add finer logic for language detection

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#80]
To `ModBOT.py`, in `discern`, we currently only choose the detected language based on the maximum likelihood. Since we want to distinguish Italian, English, and other languages, we want to "boost" the likelihood of Italian and English wrt other languages if their detected likelihood is similar (e.g. Swedish=48%, English=43% should give us English).  
Proposed method: standard deviation comparison.

**Comment by papadeiv** [comment]
Commit [27a236f](https://github.com/WEEE-Open/skeeelled/commit/27a236f3fc9d4f9b685a6c15afe3859c11988cd7).
