### ISSUE TITLE
Add English language toxicity detection model

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#81]
Find the best STEM-oriented English language toxicity detection / sentiment analysis model on huggingface by testing a few against a given dataset. In this case, we'll probably find some engineering-specific datasets already available.

**Comment by papadeiv** [comment]
Commit [27a236f](https://github.com/WEEE-Open/skeeelled/commit/27a236f3fc9d4f9b685a6c15afe3859c11988cd7).
