### ISSUE TITLE
Add missing return statement in `Polyglot.identification`

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/skeeelled#92]
Starting from here: https://github.com/WEEE-Open/skeeelled/blob/27a236f3fc9d4f9b685a6c15afe3859c11988cd7/ml/Modali.py#L76

Either remove the `if` at line 76 or add an `else` to it which returns `None`.

**Comment by papadeiv** [comment]
Closed with commit [357c76b](https://github.com/WEEE-Open/skeeelled/commit/357c76b7933afd7f3243c3b1b7b8146b14bd2524).
